import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    marginTop: 20,
  },
  imageBackground: {
    width: '100%',
    height: 335,
    borderRadius: 16,
    overflow: 'hidden',
  },
  indicator: {
    backgroundColor: '#D9D9D9',
    marginVertical: 0,
    width: 60,
    height: 2,
    alignSelf: 'center',
    marginBottom: 14,
  },
  body: {
    flex: 1,
    marginHorizontal: 24,
  },
  header: {
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  txtTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 18,
    fontWeight: '600',
    color: 'white',
  },
  title: {
    fontFamily: 'Poppins',
    fontSize: 32,
    fontWeight: '700',
    color: 'white',
    lineHeight: 38,
  },
  subTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '500',
    color: 'white',
    lineHeight: 22.4,
  },
  titleContainer: {
    padding: 24,
    justifyContent: 'center',
    paddingTop: 65,
  },
  population: {
    height: 50,
    borderRadius: 48,
    backgroundColor: 'white',
    marginTop: -25,
    marginHorizontal: 24,
    marginBottom: 32,
    shadowOffset: {x: 2, y: 2},
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowRadius: 4,
    shadowOpacity: 1,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  totalPop: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(0, 0, 0, 0.4)',
    lineHeight: 16.4,
  },
  totalPerson: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 10,
    fontWeight: '700',
    color: 'black',
    lineHeight: 16.4,
  },
  btn: {
    padding: 8,
    borderRadius: 24,
    backgroundColor: '#ff6651',
  },
  btnTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '700',
    color: 'white',
    lineHeight: 18,
  },
  citizen: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '600',
    color: '#010101',
    opacity: 0.4,
    lineHeight: 18,
  },
  successAlert: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    backgroundColor: '#353637',
    marginHorizontal: 24,
    paddingHorizontal: 8,
    borderRadius: 48,
    height: 48,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  successTxt: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    color: 'white',
    lineHeight: 16,
    marginLeft: 12,
  },
  undo: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '700',
    color: 'white',
    lineHeight: 16,
    marginRight: 20,
  },
});
