import {SCREEN_HEIGHT} from 'helper/utils';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    height: SCREEN_HEIGHT * 0.69,
    backgroundColor: '#ffffff20',
    borderRadius: 28,
  },
  header: {
    position: 'absolute',
    top: 16,
    left: 18,
    right: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
  },
  groupName: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 26,
    color: 'white',
  },
  requestTxt: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 14,
    color: 'white',
  },
  requestBtn: {
    width: 113,
    height: 41,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff20',
  },
  indicator: {
    marginTop: 50,
    flexDirection: 'row',
    alignItems: 'center',
  },
  indicatorItem: {
    flex: 1,
    height: 4,
    borderRadius: 8,
    backgroundColor: 'white',
    marginHorizontal: 2,
  },
  selectedIndicatorItem: {
    flex: 1,
    height: 4,
    borderRadius: 8,
    backgroundColor: 'white',
    opacity: 0.4,
    marginHorizontal: 2,
  },
  userInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: 'white',
    marginRight: 10,
    overflow: 'hidden',
  },
  userName: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 19,
    color: 'white',
  },
  userTime: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 14,
    color: 'white',
  },
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftViewContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  leftView: {
    width: 70,
    alignItems: 'center',
    backgroundColor: 'white',
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
    padding: 16,
    zIndex: -1,
  },
  country: {
    width: 32,
    height: 32,
    borderRadius: 32,
    backgroundColor: '#00000020',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  bottomLeftView: {
    alignSelf: 'flex-end',
  },
  countryMore: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 19,
    color: 'black',
  },
  rightView: {
    position: 'absolute',
    right: 19,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  selectedThumb: {
    width: 50,
    height: 50,
    borderRadius: 4,
    backgroundColor: '#ffffff30',
    alignSelf: 'center',
    marginBottom: 8,
    borderWidth: 4,
    borderColor: 'white',
    overflow: 'hidden',
  },
  thumb: {
    width: 40,
    height: 40,
    borderRadius: 4,
    backgroundColor: '#ffffff30',
    alignSelf: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  bottomView: {
    position: 'absolute',
    bottom: 0,
    zIndex: 1,
    left: 18,
    right: 18,
  },
  viewPostWrap: {
    paddingHorizontal: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff20',
    borderRadius: 32,
    height: 32,
    marginBottom: 12,
  },
  replyTxt: {
    fontFamily: 'Poppins',
    fontWeight: '400',
    fontSize: 12,
    color: '#ffffff80',
    marginLeft: 10,
  },
  viewPost: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 12,
    color: '#ffffff',
  },
  bgImage: {
    borderRadius: 28,
  },
});
