import {SCREEN_WIDTH} from 'helper/utils';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  background: {
    position: 'absolute',
    top: 0,
    left: -24,
    width: SCREEN_WIDTH + 52,
    height: 237,
  },
  mainContent: {
    flex: 1,
    backgroundColor: 'black',
    paddingBottom: 80,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    height: 70,
  },
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookMarkIcon: {
    marginLeft: 20,
  },
  content: {
    marginTop: 20,
    padding: 16,
  },
  largeBadge: {
    backgroundColor: '#ffffff20',
    borderRadius: 32,
    padding: 8,
    marginRight: 8,
  },
  largeBadgeLabel: {
    color: 'white',
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'Poppins',
    fontWeight: 'bold',
  },
  smallBadge: {
    borderRadius: 32,
    padding: 8,
    paddingVertical: 3,
    marginLeft: 7,
  },
  smallBadgeLabel: {
    color: 'white',
    fontSize: 10,
    lineHeight: 12,
    fontFamily: 'Poppins',
    fontWeight: '500',
  },
  byLabel: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 16.8,
    color: '#ffffff90',
  },
  mail: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 16.8,
    color: '#ffffff',
  },
  description: {
    marginTop: 8,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 19.2,
    color: '#ffffff90',
  },
  descEmail: {
    marginTop: 8,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 19.2,
    color: '#ff6651',
  },
  createYours: {
    width: '100%',
    height: 44,
    backgroundColor: '#1d1f20',
    borderRadius: 8,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    marginTop: 12,
    zIndex: 2,
  },
  likeCount: {
    marginLeft: 8,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 19.2,
    color: '#ffffff',
  },
  created: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 19.2,
    color: '#ffffff80',
  },
  voiceDescription: {
    alignItems: 'center',
    marginVertical: 9,
  },
  voiceLabel: {
    marginLeft: 8,
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 19.2,
    color: '#ffffff60',
  },
  voiceLabelBold: {
    marginLeft: 8,
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 19.2,
    color: '#ffffff',
  },
  actionContainer: {
    marginVertical: 8,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnActionTxt: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 19.2,
    color: '#ffffff',
    marginStart: 8,
  },
  btnAction: {
    width: 110,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginEnd: 8,
  },
  waveProgress: {
    marginTop: 16,
    marginBottom: 40,
  },
  userContainer: {
    padding: 16,
    backgroundColor: '#171717',
    borderRadius: 32,
  },
  tabContainer: {
    flexDirection: 'row',
    height: 54,
    marginBottom: 20,
  },
  tab1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: 'white',
  },
  tabSpace: {
    paddingLeft: 10,
  },
  tab2: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: '#ffffff50',
  },
  agree: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22.4,
    marginHorizontal: 10,
    color: 'white',
  },
  disagree: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22.4,
    marginHorizontal: 10,
    color: '#ffffff50',
  },

  winBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 32,
  },
  winLabel: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16.8,
    marginLeft: 4,
    color: 'white',
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
  },
  title: {
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 16.8,
    marginLeft: 4,
    color: 'white',
    opacity: 0.6,
  },
  emoUsersContainer: {
    width: '100%',
    height: 54,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffffff30',
    marginTop: 21,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  emoUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#171717',
    marginRight: -8,
  },
  emoUserDesc: {
    flex: 1,
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 14.4,
    marginLeft: 16,
    color: '#ffffff80',
  },
  bottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 74,
    backgroundColor: '#171717',
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  newButton: {
    width: '100%',
    height: 42,
    backgroundColor: '#ff6651',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  mediaWrap: {
    height: 330,
    backgroundColor: 'white',
    borderRadius: 24.75,
    overflow: 'hidden',
  },
  mediaImg: {
    width: '100%',
    height: '100%',
  },
  newButtonTitle: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
    lineHeight: 18,
    marginLeft: 4,
  },
  audioPlayBtnWrapper: {
    display: 'flex',
    alignItems: 'center',
    marginTop: -24,
    zIndex: 1,
  },
  audioPlayBtn: {
    backgroundColor: 'black',
    borderRadius: 40,
  },
  showMoreButton: {
    width: '100%',
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 32,
    marginTop: 12,
    backgroundColor: '#94b3d130',
  },
  showMoreText: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    color: '#ffffff80',
    lineHeight: 18,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successTxtContainer: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 36,
    color: '#ffffff',
    textAlign: 'center',
  },
  successTxt: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 36,
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 40,
  },
  playerView: {
    width: SCREEN_WIDTH - 80,
    height: SCREEN_WIDTH - 80,
    backgroundColor: '#494949',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  },
  controlView: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  slider: {
    height: 20,
    flex: 1,
    marginHorizontal: 4,
  },
  txtSliderTime: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 6,
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.4,
  },
  emoView: {
    position: 'absolute',
    right: -10,
    top: -10,
    width: 60,
    height: 60,
    borderRadius: 60,
    backgroundColor: '#F3F4F5',
    borderColor: '#010101',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emojiSelectedTxt: {
    fontSize: 35,
  },
  emojiView: {
    flex: 1,
    width: '100%',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    marginTop: 24,
    padding: 12,
  },
  successViewDismiss: {
    width: 220,
    height: 45,
    borderRadius: 45,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 60,
  },
  successViewDismissTxt: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  successEmoView: {
    position: 'absolute',
    right: -10,
    top: -10,
    width: 60,
    height: 60,
    borderRadius: 60,
    backgroundColor: '#F3F4F5',
    borderColor: '#010101',
    justifyContent: 'center',
    alignItems: 'center',
  },
  downloadView: {
    position: 'absolute',
    top: 100,
    width: '100%',
    left: 0,
    backgroundColor: 'transparent',
  },
  downloadBody: {
    marginHorizontal: 16,
    height: 50,
    backgroundColor: '#27292A',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  downloadDescTxt: {
    flex: 1,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.8)',
    marginStart: 10,
  },
  downloadStatusView: {
    alignItems: 'flex-end',
  },
  downloadSlider: {
    marginTop: -20,
    marginHorizontal: 20,
  },
});
