import {SCREEN_HEIGHT, SCREEN_WIDTH, STATUS_BAR_HEIGHT} from 'helper/utils';
import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  shareView: {
    width: '100%',
    height: '100%',
    backgroundColor: '#13162BCC',
    blurRadius: 100,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  shareContainer: {
    width: '100%',
    flex: 1,
    backdropFilter: 'blur(10)',
  },
  closeBtn: {
    marginTop: 50,
    marginRight: 20,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  body: {
    display: 'flex',
    marginHorizontal: 20,
  },
  successBody: {
    display: 'flex',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 100,
  },
  titleContainer: {
    display: 'flex',
    alignItems: 'center',
  },
  title: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 32,
    color: '#FFFFFF',
  },
  subTitle: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    color: '#FFFFFF',
    marginTop: 14,
  },
  playlistContainer: {
    marginTop: 0,
    marginBottom: Platform.OS === 'android' ? 150 : 400,
  },
  actionView: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 20,
  },
  actionItemContainer: {
    display: 'flex',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  actionItem: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBar: {
    width: '85%',
    marginTop: 62,
  },
  contactsContainer: {
    width: '90%',
    marginTop: 50,
  },
  btnEditSave: {
    borderRadius: 30,
    background: 'linear-gradient(137.57deg, #F6943D 6.81%, #F85B2B 92.63%)',
    height: 50,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnEditSaveText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
  },
  successImage: {
    marginTop: 20,
  },
  successText: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 32,
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 20,
  },
  playlistNameText: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 32,
    color: '#F85B2B',
    textAlign: 'center',
  },
  editContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#13162BCC',
    blurRadius: 100,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  editMainContainer: {
    width: '100%',
    height: '100%',
    backdropFilter: 'blur(22)',
  },
  editContent: {
    flex: 1,
    padding: 20,
  },
  editTitle: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 32,
    textAlign: 'center',
    color: '#FFFFFF',
    marginBottom: 40,
  },
  editDescription: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 22,
    textAlign: 'center',
    color: '#C7C7C7',
  },
  editTabList: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  tabSel: {
    borderBottomWidth: 2,
    borderColor: '#F6943D',
    marginHorizontal: 20,
    paddingBottom: 8,
  },
  tabSelText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  tab: {
    marginHorizontal: 20,
    paddingBottom: 8,
  },
  tabText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 18,
    color: '#A7A7A7',
  },
  editTabContent: {},
  editInputGroup: {
    marginTop: 25,
  },
  editInputLabel: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    color: '#FFFFFF',
    marginBottom: 16,
  },
  editInputText: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 8,
    paddingHorizontal: 25,
    paddingVertical: 18,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
  },
  editSocialInput: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editSocialInputText: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 8,
    paddingLeft: 25,
    paddingRight: 60,
    paddingVertical: 18,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
    flex: 1,
  },
  editSocialIcon: {
    position: 'absolute',
    right: 25,
  },
  editInputImage: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 8,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editInputImageAction: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editInputImageText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 18,
  },
  editInputImageDesc: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
  },
  editInputImageDescText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    color: '#C7C7C7',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#13162BCC',
  },
  loadingMainContainer: {
    width: '100%',
    height: '100%',
    backdropFilter: 'blur(22)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingContent: {
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingTitle: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 32,
    color: '#FFFFFF',
  },
  loadingDescription: {
    marginTop: 16,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 22,
    color: '#C7C7C7',
    textAlign: 'center',
  },
  editImagePreviewContianer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 8,
    height: 112,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editImagePreview: {
    display: 'flex',
    width: '100%',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editImageSelected: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  editImageSelectedFileName: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
    flex: 0.9,
    marginStart: 10,
  },
  editThumnailPreview: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  editCoverPreview: {},
  cardContainer: {
    marginTop: 28,
  },
  actionContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  textCreatePlayList: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    color: '#FFFFFF',
    marginLeft: 15,
  },
  searchContainer: {
    width: '100%',
    height: '100%',
    backdropFilter: 'blur(10)',
  },

  // Process Image
  topOptionsWrapper: {
    height: 50 + STATUS_BAR_HEIGHT,
    paddingTop: STATUS_BAR_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    zIndex: 1,
    width: '100%',
    paddingHorizontal: 20,
  },
  btnTopOption: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelOptionsWrapper: {
    width: '100%',
    height: SCREEN_HEIGHT - STATUS_BAR_HEIGHT - 50,
    position: 'absolute',
    top: '100%',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    overflow: 'hidden',
    left: 0,
  },
  labelOptionsTitleWrapper: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dragBar: {
    marginTop: 15,
    width: 50,
    height: 3,
    borderRadius: 1,
    backgroundColor: '#fff',
  },
  labelOptionsSearchWrapper: {
    height: 44,
    flexDirection: 'row',
    width: SCREEN_WIDTH - 30,
    marginHorizontal: 15,
    borderBottomColor: '#fff',
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  labelOptionsSearch: {
    fontSize: 16,
    color: '#fff',
    width: SCREEN_WIDTH - 30 - 44,
  },
  searchIcon: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelItemWrapper: {
    width: SCREEN_WIDTH / 3,
    height: SCREEN_WIDTH / 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainLabel: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    height: 36,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  bottomOptionsWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    height: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 15,
  },
  textToolWrapper: {
    position: 'absolute',
    zIndex: 1,
    top: 0,
    left: 0,
    height: SCREEN_HEIGHT,
    width: SCREEN_WIDTH,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'space-between',
  },
  textTopOptions: {
    flexDirection: 'row',
    height: 50 + STATUS_BAR_HEIGHT,
    paddingTop: STATUS_BAR_HEIGHT,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textWrapper: {
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textBottompOptions: {
    minHeight: 36,
    marginVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  circleSelectedColor: {
    width: 36,
    marginHorizontal: 5,
    height: 36,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleTextColor: {
    height: 24,
    width: 24,
    borderRadius: 24,
    borderColor: '#fff',
    borderWidth: 2,
    marginHorizontal: 5,
  },
  scrollView: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  backgroundContainer: {
    overflow: 'hidden',
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedImageWrapper: {
    paddingHorizontal: 5,
    bottom: 0,
    left: 0,
    position: 'absolute',
    width: '100%',
    height: 100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    zIndex: 10,
  },
  previewImageWrapper: {
    marginHorizontal: 5,
    borderRadius: 5,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    height: 54,
    width: 32,
  },
  previewMultiImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 5,
  },
});
