import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  header: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    zIndex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginEnd: 40,
  },
  userBackground: {
    width: '140%',
    height: 142,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  avatarWrap: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    top: 90,
    overflow: 'hidden',
  },
  userImage: {
    width: '100%',
    height: '100%',
  },
  userName: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 21,
    textAlign: 'center',
    color: 'white',
  },
  userStatus: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  countryWrap: {
    width: 24,
    height: 24,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: 'grey',
  },
  userInfo: {
    marginTop: 100,
    alignItems: 'center',
  },
  userStatusTxt: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 19,
    color: 'white',
    marginLeft: 7,
    marginRight: 12,
  },
  userFollowing: {
    height: 40,
    borderRadius: 16,
    backgroundColor: '#25272d',
    marginTop: 15,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  followersTxt: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    color: 'white',
    opacity: 0.6,
    marginLeft: 8,
  },
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentWrap: {
    marginTop: 29,
    paddingHorizontal: 16,
  },
  contentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  contentHeaderTxt: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 12,
    color: 'white',
    marginLeft: 9,
  },
  seeAll: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    color: '#bf76f9',
  },
  content: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  followBtn: {
    paddingHorizontal: 16,
    height: 30,
    backgroundColor: '#b767f9',
    borderRadius: 48,
    justifyContent: 'center',
  },
  followAll: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    fontSize: 12,
    color: 'white',
  },
  badge: {
    height: 30,
    borderRadius: 16,
    backgroundColor: '#25272d',
    paddingHorizontal: 12,
    justifyContent: 'center',
    marginRight: 8,
  },
  badgeTxt: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    color: 'white',
  },
  subTitle6: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  aroundWorldMainContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    marginTop: 24,
    marginBottom: 64,
    marginLeft: 8,
  },
  countryWheel: {
    width: '30%',
    margin: 5,
  },
  noData: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  wheelView: {
    marginVertical: 16,
    marginRight: 24,
  },
  privateTxt: {
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '400',
    color: '#ffffff80',
    marginTop: 15,
  },
  privateWrap: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
