const Images = {
    marker: require('../assets/images/marker.png'),
    circleMarker: require('../assets/images/circleMarker.png'),
    currentLocation: require('../assets/images/currentLocation.jpeg'),
    headPhones: require('../assets/images/headPhones.png'),
    listening: require('../assets/images/listening.png'),
    polygonFrame: require('../assets/images/polygonFrame.png'),
    users: require('../assets/images/users.png'),
    filter: require('../assets/images/filter.png'),
    search: require('../assets/images/search.png'),
    headPhonesGrey: require('../assets/images/headPhonesGrey.png'),
    headPhonesWhite: require('../assets/images/headPhonesWhite.png'),
    radioWhite: require('../assets/images/radioWhite.png'),
    radioGrey: require('../assets/images/radioGrey.png'),
    playCircleWhite: require('../assets/images/playCircleWhite.png'),
    playCircleGrey: require('../assets/images/playCircleGrey.png'),
    playGrey: require('../assets/images/playGrey.png'),
    refresh: require('../assets/images/refresh.png'),
    playerBg: require('../assets/images/playerBg.png'),
}
export default Images