import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#010101',
    borderRadius: 30,
    marginHorizontal: 0,
  },
  indicator: {
    backgroundColor: '#D9D9D9',
    marginVertical: 0,
    width: 60,
    height: 2,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flexCenterRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scrollContainer: {
    padding: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginEnd: 40,
  },
  titleCenter: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
  },
  myTrendingContainer: {
    marginTop: 40,
  },
  myTrendingSubContainer: {
    marginTop: 16,
    marginLeft: -16,
  },
  trendingAudioContainer: {
    marginTop: 32,
  },
  aroundWorldContainer: {
    marginTop: 32,
  },
  aroundWorldMainContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 24,
    marginBottom: 64,
    marginLeft: 8,
  },
  helperContainer: {
    marginLeft: 8,
  },
  subTitle1: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  subTitle2: {
    fontSize: 9,
    fontWeight: '500',
    color: '#ffffff80',
    marginTop: 7,
  },
  subTitle3: {
    fontSize: 8,
    fontWeight: '500',
    color: '#ffffff40',
    marginTop: 1,
  },
  subTitle4: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
  },
  subTitle5: {
    fontSize: 8,
    fontWeight: '500',
    color: '#FF6651',
  },
  subTitle6: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  subTitle7: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  trendAudioTitle: {
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '500',
    color: '#fff',
    marginBottom: 4,
    lineHeight: 16.8,
  },
  trendNumber: {
    fontFamily: 'Poppins',
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    lineHeight: 21.6,
  },
  trendView: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '400',
    color: '#ffffff50',
    lineHeight: 14.4,
    marginLeft: 8,
  },
  // trendAudioPercent: {
  //   marginTop: 10,
  //   fontFamily: 'Poppins',
  //   fontSize: 12,
  //   fontWeight: '400',
  //   color: '#08b883',
  //   lineHeight: 12,
  // },
  // trendAudioLastweek: {
  //   marginTop: 10,
  //   fontFamily: 'Poppins',
  //   fontSize: 12,
  //   fontWeight: '400',
  //   color: '#ffffff80',
  //   lineHeight: 12,
  //   marginLeft: 4,
  // },
  spaceView: {
    marginTop: 16,
  },
  trendHot: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff20',
    height: 40,
    borderRadius: 8,
    width: 310,
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    borderTopColor: '#ffffff30',
    borderTopWidth: 2,
    borderLeftColor: '#ffffff30',
    borderLeftWidth: 1,
    borderRightColor: '#ffffff30',
    borderRightWidth: 1,
  },
  trendHotIcon: {
    backgroundColor: '#8210DC',
    width: 24,
    height: 24,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  trendAudio: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff20',
    height: 100,
    borderRadius: 8,
    width: 310,
    justifyContent: 'space-between',
    paddingRight: 16,
    borderTopColor: '#ffffff30',
    borderTopWidth: 2,
    borderLeftColor: '#ffffff30',
    borderLeftWidth: 1,
    borderRightColor: '#ffffff30',
    borderRightWidth: 1,
  },
  trendEmolike: {
    flexDirection: 'column',
    backgroundColor: '#ffffff20',
    height: 76,
    borderRadius: 8,
    width: 310,
    justifyContent: 'center',
    borderTopColor: '#ffffff30',
    borderTopWidth: 2,
    borderLeftColor: '#ffffff30',
    borderLeftWidth: 1,
    borderRightColor: '#ffffff30',
    borderRightWidth: 1,
  },
  trendEmolikeCounts: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 12,
  },
  citizen: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  trendInfo: {
    marginTop: 16,
    alignSelf: 'center',
  },
  trendViewer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  trendPercent: {
    color: '#08B883',
    marginLeft: 8,
  },
  emoLikesWrap: {
    width: 1,
    height: 52,
    backgroundColor: '#ffffff10',
    marginHorizontal: 16,
  },
  emoLikes: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  emoLikesUser: {
    width: 24,
    maxHeight: 24,
    borderRadius: 50,
    marginRight: 10,
    backgroundColor: 'grey',
  },
  wheelView: {
    marginVertical: 16,
    marginRight: 24,
  },
  countryWheel: {
    width: '30%',
    margin: 5,
  },
  noData: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  blueBackground: {
    position: 'absolute',
    top: 0,
    right: -20,
    borderRadius: 20,
  },
  redBackground: {
    position: 'absolute',
    top: 60,
    left: -20,
  },
  createPostBtnWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 10,
    alignItems: 'center',
  },
  trendingAudioBackBtn: {position: 'absolute', left: 10, top: -4, zIndex: 1},
  allCountriesMainContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  playAudioBtn: {
    width: 48,
    height: 48,
    backgroundColor: '#ff6651',
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
