import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    paddingTop: 64,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  flexRow: {
    flexDirection: 'row',
  },
  flexRowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexRowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mainContent: {
    flex: 1,
    backgroundColor: 'black',
    paddingBottom: 80,
  },
  topicContainer: {
    padding: 12,
    backgroundColor: '#20232C',
    borderRadius: 10,
    marginTop: 17,
    marginBottom: 32,
  },
  topicTagImage: {width: 24, height: 24, borderRadius: 50, marginRight: 4},
  topicTagBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 32,
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginRight: 4,
  },
  topicCreatorImage: {width: 48, height: 48, borderRadius: 50},
  threadStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 16,
    // paddingVertical: 16,
  },
  threadStatusText: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
    color: '#ffffff80',
    marginLeft: 4,
  },
  smallAudioPlay: {
    fontFamily: 'Poppins',
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff',
  },
  smallAudioPlayButton: {
    width: 90,
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 24,
    backgroundColor: '#ff6651',
    paddingHorizontal: 10,
  },
  topicPreviewImage: {width: 80, height: 80, borderRadius: 8, marginRight: 4},
  text1: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff60',
  },
  text2: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  text3: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff40',
    marginTop: 4,
  },
  text4: {
    fontSize: 12,
    fontWeight: '400',
    color: '#ffffff70',
  },
  userContainer: {
    marginTop: 34,
    // padding: 16,
    // backgroundColor: '#171717',
    // borderRadius: 32,
  },
  tabContainer: {
    flexDirection: 'row',
    height: 54,
    marginBottom: 20,
  },
  tab1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: 'white',
  },
  tabSpace: {
    paddingLeft: 10,
  },
  tab2: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: '#ffffff50',
  },
  agree: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22.4,
    marginHorizontal: 10,
    color: 'white',
  },
  disagree: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22.4,
    marginHorizontal: 10,
    color: '#ffffff50',
  },
  winBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 32,
  },
  winLabel: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16.8,
    marginLeft: 4,
    color: 'white',
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
  },
  //   title: {
  //     fontFamily: 'Poppins',
  //     fontSize: 14,
  //     fontWeight: '600',
  //     lineHeight: 16.8,
  //     marginLeft: 4,
  //     color: 'white',
  //     opacity: 0.6,
  //   },
  seeAll: {
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 16.8,
    marginLeft: 4,
    color: '#ff6651',
  },
  plusButton: {
    marginRight: 10,
    height: 103,
    justifyContent: 'center',
  },
  emolikeContainer: {
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff20',
  },
  emolike: {
    width: 80,
    height: 103,
    borderRadius: 8,
    backgroundColor: 'grey',
    marginRight: 12,
  },
  emoti: {
    width: 24,
    height: 24,
    borderRadius: 24,
    backgroundColor: 'white',
    position: 'absolute',
    right: 4,
    top: -4,
  },
  emoNameContaner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
  },
  emoName: {
    fontFamily: 'Poppins',
    fontSize: 8,
    fontWeight: '500',
    lineHeight: 11.2,
    marginLeft: 4,
    color: '#ffffff40',
  },
  emoUsersContainer: {
    width: '100%',
    height: 54,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffffff30',
    marginTop: 21,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  emoUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#171717',
    marginRight: -8,
  },
  emoUserDesc: {
    flex: 1,
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 14.4,
    marginLeft: 16,
    color: '#ffffff80',
  },

  showMoreButton: {
    width: '100%',
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 32,
    marginTop: 12,
    backgroundColor: '#94b3d130',
  },
  showMoreText: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 12,
    color: '#ffffff80',
    lineHeight: 18,
  },
  bottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 74,
    backgroundColor: '#171717',
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  newButton: {
    width: '100%',
    height: 42,
    backgroundColor: '#ff6651',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  newButtonTitle: {
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
    lineHeight: 18,
    marginLeft: 4,
  },
});
