import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  root: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
  backgroundContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  imageContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    paddingBottom: 200,
  },
  imageView: {
    width: '100%',
    height: '100%',
  },
  effectView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    paddingBottom: 200,
  },
  headerFilter: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 200,
  },
  backgroundLight: {position: 'absolute', top: 0, right: 0, bottom: 0},
  mainContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 57,
    paddingHorizontal: 35,
  },
  txtHavingTrouble: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  txtGetHelp: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    color: '#ffffff',
  },
  btnContainer: {
    width: '100%',
    height: 80,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 54,
  },
  btnBgEffect: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 27,
    borderWidth: 0,
  },
  btnSubmit: {
    width: '100%',
    height: 54,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 27,
  },
  buttonText: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: '#ffffff',
    textAlign: 'center',
    marginStart: 28,
  },
  txtDesc: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.6)',
    textAlign: 'center',
    marginBottom: 42,
  },
  txtAppName: {
    fontFamily: 'MonumentExtended-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: 10,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 20,
  },
});
