import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    marginHorizontal: 24,
  },
  backBtn: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  txtTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  topView: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 25,
    backgroundColor: 'white',
    marginTop: 21,
    marginHorizontal: 21,
    padding: 9,
  },
  txtCreationEnergy: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '700',
    color: '#000000',
    opacity: 0.4,
    marginStart: 12,
  },
  txtCountry: {
    flex: 1,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '700',
    color: '#000000',
    textAlign: 'right',
  },
  btnCreate: {
    width: 67,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FF6651',
    justifyContent: 'center',
    alignItems: 'center',
    marginStart: 12,
  },
  txtCreate: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  createHintContainer: {
    backgroundColor: 'white',
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 24,
    marginTop: 32,
    zIndex: 99,
  },
  createHintTopIcon: {
    position: 'absolute',
    top: -15,
    alignSelf: 'center'
  },
  createHint: {
    color: '#000000',
    fontFamily: 'Poppins',
    fontWeight: '600',
    lineHeight: 21.6,
    fontSize: 18,
    marginBottom: 8,
  },
  createSubHint: {
    color: '#000000',
    fontFamily: 'Poppins',
    fontWeight: '400',
    lineHeight: 19.2,
    fontSize: 12,
  },
  btnContinue: {
    width: '100%',
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF6651',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 4,
  },
  txtBtnCreate: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
});
