import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 0,
  },
  indicator: {
    backgroundColor: '#D9D9D9',
    marginVertical: 0,
    width: 60,
    height: 2,
  },
  title: {
    flex: 1,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
  },
  infoView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 10,
  },
  txtInvite: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  txtShowAll: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '600',
    color: '#FF6651',
  },
  txtMemberName: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(0, 0, 0, 1)',
    marginTop: 8,
  },
  btnStartNowContainer: {
    width: '100%',
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FF6651',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  btnScheduleContainer: {
    width: '100%',
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#FF6651',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  btnStartNowText: {
    flex: 1,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 1)',
    textAlign: 'center',
  },
  addTopicInput: {
    width: '100%',
    height: 50,
    fontSize: 20,
    color: 'white',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign: 'center',
    marginHorizontal: 10,
    marginVertical: 20,
  },
  txtLeaveRoom: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(0, 0, 0, 0.6)',
    marginStart: 8,
  },
  txtInviteUser: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    color: '#FF6651',
    marginStart: 8,
  },
});
