import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  body: {
    flex: 1,
    margin: 24,
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 8,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  indicator: {
    backgroundColor: '#D9D9D9',
    marginVertical: 0,
    width: 60,
    height: 2,
    alignSelf: 'center',
    marginBottom: 14,
  },
  topView: {
    width: 76,
    height: 76,
    borderRadius: 16,
    backgroundColor: '#F3F4F5',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtNewWorld: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginTop: 8,
  },
  txtDesc: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 19,
    fontWeight: '400',
    color: '#000000',
    marginTop: 8,
  },
  btnContinue: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF6651',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 4,
  },
  btnCancel: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginRight: 4,
  },
  txtBtnCreate: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  txtBtnCancel: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(0, 0, 0, 0.4)',
  },
  flagContainer: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  flagColorTxt: {
    fontFamily: 'Poppins',
    color: '#000000',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 14,
    marginBottom: 8,
  },
  buttons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
