import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  root: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
  mainContainer: {
    flex: 1,
    width: '100%',
  },
  headerContainer: {
    position: 'absolute',
    top: 20,
    left: 0,
    width: '100%',
    paddingRight: 20,
    paddingLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  actions: {
    flexDirection: 'row',
  },
  container: {
    width: '100%',
    height: 200,
    position: 'relative',
  },
  background: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  bgImage: {
    width: '100%',
    height: '100%',
  },
  content: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    paddingHorizontal: 20,
    justifyContent: 'flex-end',
  },
  info: {
    width: '100%',
    marginBottom: -45,
    flexDirection: 'row',
    alignItems: 'center',
  },
  userImageContainer1: {
    width: 130,
    height: 130,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 65,
    borderWidth: 1,
    borderColor: 'rgba(47, 155, 255, 0.2)',
  },
  userImageContainer2: {
    width: 120,
    height: 120,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(47, 155, 255, 0.3)',
  },
  userImageContainer3: {
    width: 110,
    height: 110,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 55,
    borderWidth: 1,
    borderColor: 'rgba(47, 155, 255, 0.5)',
  },
  userImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  detail: {flex: 1},
  detailInfo: {
    marginStart: 20,
  },
  detailInfoName: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: 18,
    color: '#FFFFFF',
  },
  detailInfoNick: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    color: '#FFFFFF',
    opacity: 0.7,
    marginTop: 6,
  },
  actionsView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
  },
  detailAction: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnEdit: {
    width: 110,
    height: 37,
    backgroundColor: '#FA347C',
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnEditText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: '#FFFFFF',
  },
  playBtn: {
    position: 'absolute',
    bottom: -30,
    right: 25,
  },
  title: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
    marginTop: 30,
  },
  descriptionContainer: {
    marginTop: 50,
    paddingHorizontal: 20,
  },
  description: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
    color: '#A7A7A7',
  },
  followInfoContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
  },
  followersContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  followingContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginStart: 15,
  },
  txtBoldFollow: {
    color: 'white',
    fontWeight: '700',
    fontSize: 14,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  txtNormalFollow: {
    color: 'white',
    fontWeight: '400',
    fontSize: 12,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    opacity: 0.6,
    marginStart: 5,
  },
  actionFollowContainer: {
    marginTop: 24,
  },
  btnFollow: {
    backgroundColor: '#ffffff',
    width: '100%',
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  txtBtnFollow: {
    color: '#010101',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  btnFollowing: {
    width: '100%',
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  txtBtnFollowing: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
    zIndex: 1000,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  listeningConatiner: {
    flex: 1,
    height: 75,
    display: 'flex',
    justifyContent: 'center',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderRadius: 8,
    marginTop: 24,
    paddingHorizontal: 12,
  },
  txtNowListening: {
    top: -10,
    left: 10,
    paddingHorizontal: 5,
    color: 'white',
    fontSize: 10,
    lineHeight: 15,
    position: 'absolute',
    backgroundColor: '#000000',
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  listenItemContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 42,
    justifyContent: 'center',
  },
  itemImage: {
    width: 42,
    height: 42,
  },
  itemInfoContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginStart: 12,
  },
  itemUserName: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  itemUserInfo: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '300',
    opacity: 0.6,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
  },
  resourceContainer: {
    marginTop: 24,
  },
  resourceTab: {
    height: 50,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 25,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    paddingHorizontal: 4,
  },
  selectedResourceTab: {
    flex: 1,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  selectedResourceTabText: {
    color: 'white',
    fontWeight: '600',
    lineHeight: 18,
  },
  defaultResourceTab: {
    flex: 1,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  defaultResourceTabText: {
    color: 'white',
    opacity: 0.4,
    fontWeight: '600',
    lineHeight: 18,
  },
  postResourceView: {
    display: 'flex',
    marginTop: 24,
  },
  postLayoutFirst: {
    flexDirection: 'row',
  },
  postLayoutSecond: {
    flexDirection: 'row',
  },
  activityResourceView: {
    marginTop: 24,
  },
  editContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#13162BCC',
    blurRadius: 100,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  editMainContainer: {
    width: '100%',
    height: '100%',
    backdropFilter: 'blur(22)',
  },
  closeBtn: {
    marginTop: 70,
    marginRight: 20,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  editContent: {
    flex: 1,
    padding: 20,
  },
  editTitle: {
    fontFamily:
      Platform.OS === 'android' ? "'PP Right Grotesk'" : 'RightGrotesk-Medium',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 32,
    textAlign: 'center',
    color: '#FFFFFF',
    marginBottom: 40,
  },
  editTabList: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  tabSel: {
    borderBottomWidth: 2,
    borderColor: '#F6943D',
    marginHorizontal: 20,
    paddingBottom: 8,
  },
  tabSelText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  tab: {
    marginHorizontal: 20,
    paddingBottom: 8,
  },
  tabText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 18,
    color: '#A7A7A7',
  },
  editTabContent: {},
  editInputGroup: {
    marginTop: 25,
  },
  editInputLabel: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    color: '#FFFFFF',
    marginBottom: 16,
  },
  editInputText: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 8,
    paddingHorizontal: 25,
    paddingVertical: 18,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
  },
  editSocialInput: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editSocialInputText: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 8,
    paddingLeft: 25,
    paddingRight: 60,
    paddingVertical: 18,
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
    flex: 1,
  },
  editSocialIcon: {
    position: 'absolute',
    right: 25,
  },
  btnEditSave: {
    borderRadius: 30,
    background: 'linear-gradient(137.57deg, #F6943D 6.81%, #F85B2B 92.63%)',
    height: 50,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 70,
  },
  btnEditSaveText: {
    fontFamily: Platform.OS === 'android' ? "'PP Pangram Sans'" : 'Pangram',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    color: '#FFFFFF',
  },
});
