import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginHorizontal: 0,
  },
  indicator: {
    backgroundColor: '#D9D9D9',
    marginVertical: 0,
    width: 60,
    height: 2,
  },
  personViewContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sideImageContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: 'white',
    alignItems: 'center',
  },
  centerImageContainer: {
    width: 107,
    height: 107,
    borderRadius: 107,
    backgroundColor: 'rgba(255, 102, 81, 0.2)',
    marginHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerImageContainer1: {
    width: 107,
    height: 107,
    borderRadius: 107,
    backgroundColor: 'rgba(255, 102, 81, 0.2)',
    marginHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerImageContainer2: {
    width: 97,
    height: 97,
    borderRadius: 97,
    backgroundColor: 'rgba(255, 102, 81, 0.1)',
    marginHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerImageContainer3: {
    width: 73,
    height: 73,
    borderRadius: 73,
    backgroundColor: 'rgba(255, 102, 81, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 102, 81, 0.2)',
    marginHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  personImage: {
    width: 44,
    height: 44,
    borderRadius: 40,
    borderColor: '#fff',
    borderWidth: 2,
  },
  infoView: {
    marginTop: 20,
  },
  infoTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 18,
    fontWeight: '600',
    color: '#010101',
    textAlign: 'center',
  },
  infoDesc: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '400',
    color: '#010101',
    textAlign: 'center',
    opacity: 0.6,
  },
  playerView: {
    width: '100%',
    height: 150,
    marginTop: 24,
  },
  trackView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  trackImage: {
    width: 73,
    height: 73,
    borderRadius: 6,
  },
  trackInfo: {
    flex: 1,
    marginStart: 12,
  },
  txtNowPlaying: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '600',
    color: '#FF6651',
  },
  txtTrackTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 16,
    fontWeight: '600',
    color: '#010101',
    marginVertical: 2,
  },
  txtTrackArtist: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    color: '#010101',
    opacity: 0.6,
  },
  onQueueMainContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  txtOnQueue: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '600',
    color: '#010101',
  },
  switchContianer: {
    width: 40,
    height: 24,
    borderRadius: 12,
    padding: 3,
  },
  switchCircle: {
    width: 18,
    height: 18,
    borderRadius: 18,
    marginEnd: 3,
  },
  openAudioRequestContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
  },
  txtOpenAUdioRequest: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '500',
    color: '#010101',
  },
  actionBtnContainer: {
    height: 50,
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 102, 81, 0.2)',
  },
  actionBtnTxt: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    color: '#FF6651',
    marginStart: 8,
  },
  toast: {
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  toastTxt: {
    fontSize: 12,
    color: 'white',
    paddingHorizontal: 20,
  },
  listenerContainer: {
    marginTop: 24,
  },
  listenerMainContainer: {
    marginTop: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listenerImageContainer: {flexDirection: 'row', alignItems: 'center'},
  listenerImage: {
    width: 46,
    height: 46,
    borderRadius: 40,
    marginRight: 12,
  },
  listenerIndicator: {width: '100%', alignItems: 'center', marginTop: 32},
  listenerNoDataContainer: {width: '100%', alignItems: 'center', marginTop: 8},
  listenerChatButton: {
    backgroundColor: '#FF6651',
    borderRadius: 16,
    width: 62,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listenerType1: {
    fontSize: 14,
    fontWeight: '600',
    color: '#010101',
    marginBottom: 4,
  },
  listenerType2: {
    fontSize: 12,
    fontWeight: '400',
    color: '#01010160',
  },
  listenerType3: {
    fontSize: 12,
    fontWeight: '500',
    color: '#010101',
  },
  listenerType4: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  recordControl: {
    alignItems: 'center',
  },
  control: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  controlBtn: {
    width: 67,
    height: 67,
    justifyContent: 'center',
    alignItems: 'center',
  },
  duration: {
    marginTop: 6,
    height: 22,
    paddingHorizontal: 10,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6651',
  },
  durationTxt: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    color: '#FFFFFF',
  },
  recordContainer: {
    width: 56,
    height: 56,
    borderRadius: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
